name: DVC CI/CD

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install dvc[s3]
        
    - name: Configure DVC
      run: |
        dvc remote modify --local myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        dvc remote modify --local myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Pull latest data from DVC
      run: |
        ls -ltra
        dvc pull

    # Include steps for any processing, changes, or model training
    # ...

    - name: Display the files
      run: |
        ls -ltra
        pwd

